language: minimal

dist: bionic

addons:
   apt:
      packages:
         - debhelper
         - devscripts
         - fakeroot

script: debuild -us -uc

deploy:
   provider: releases
   api_key: "$GITHUB_TOKEN"
   file:
      - "../sharp-configs_10.2.5.dsc"
      - "../sharp-configs_10.2.5.tar.xz"
      - "../sharp-configs_10.2.5_all.deb"
   skip_cleanup: true
   on:
      tags: true

